name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Executar testes
        run: npm test

  docker:
    needs: testes
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: seitiquis/cadastro-alunos:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Fazer deploy no Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
